#!/bin/sh

for i in `echo "9 16 25 49 100 196 400 784 1600"`
do
  for j in `seq 0 99`
  do
    echo Generating instance "`echo $i $j | awk '{printf("n%07di%02d.txt",$1,$2);}'`"
    java MAXCUTRandomInstanceGenerator $i > `echo $i $j | awk '{printf("n%07di%02d.txt",$1,$2);}'`
  done
done
